### Mortgage insurance proposals - local
POST http://127.0.0.1:9999/mortgage/
Content-Type: application/json

{
  "own_client": true,
  "ListOfInsured": [
    {"BirthDate": "1973", "Gender": "0", "IsSmoking": "0"},
    {"BirthDate": "1974", "Gender": "1", "IsSmoking": "1"}
  ],
  "ListOfTracks": [
    {"DesiredPeriod": 120, "DesiredSum": 500000, "InterestRate": 5, "InterestType": 1},
    {"DesiredPeriod": 240, "DesiredSum": 600000, "InterestRate": 6, "InterestType": 2}
  ]
}

### Mortgage insurance proposals - Tunbit
POST http://18.221.172.87/mortgage/
Content-Type: application/json

{
  "ListOfInsured":[
    {"BirthDate":"1973","Gender":"0","IsSmoking":"0"},
    {"BirthDate":"1974","Gender":"1","IsSmoking":"1"}],
  "ListOfTracks":[
    {"DesiredPeriod":120,"DesiredSum":500000,"InterestRate":5,"InterestType":1},
    {"DesiredPeriod":240,"DesiredSum":600000,"InterestRate":6,"InterestType":2}
  ]
}

### Mortgage insurance proposals - VPS
POST http://52.164.216.215/InsuranceService.svc/CalculateLifeInsuranceMortgage/
Content-Type: application/json

{
  "PremiumType": 1,
  "NumberOfInsured": 2,
  "ListOfInsured": [
    {"Gender": "f", "BirthDate": "1985-01-31", "IsSmoking": false}, {"Gender": "m", "BirthDate": "1982-03-04", "IsSmoking": true}
  ],
  "ListOfTracks": [
    {"DesiredSum": 600000, "DesiredPeriod": 120, "InterestType": 1, "InterestRate": 6},
    {"DesiredSum": 500000, "DesiredPeriod": 120, "InterestType": 2, "InterestRate": 5}
  ]
}


### Life insurance proposals - local
POST http://127.0.0.1:9999/life/
Content-Type: application/json

{
  "own_client": true,
  "BirthDate": "1973",
  "Gender": "0",
  "IsSmoking": "0",
  "DesiredPeriod": 20,
  "DesiredSum": 500000,
  "PremiumType": 1
}

### Life insurance proposals - Tunbit
POST http://18.221.172.87/life/
Content-Type: application/json

{
  "own_client": true,
  "BirthDate": "1973",
  "Gender": "0",
  "IsSmoking": "0",
  "DesiredPeriod": 20,
  "DesiredSum": 500000,
  "PremiumType": 1
}

### Life insurance proposals - VPS
POST http://52.164.216.215/InsuranceService.svc/CompareLifeInsuranceRates/
Content-Type: application/json

{
    "DesiredPeriod": 20,
    "DesiredSum": 500000,
    "ListOfInsured": [
        {
            "Gender": "F",
            "BirthDate": "1985-01-01",
            "IsSmoking": true
        }
    ],
    "ListOfTracks": [],
    "NumberOfInsured": 1,
    "PremiumType": 1
}


### Content insurance proposals
POST http://18.221.172.87/content/
Content-Type: application/json

{
  "c_type_floor": 4,
  "c_mid_floor": 4,
  "c_ins_sum": 1500000,
  "c_prev_claims": 1
}


### Building insurance proposals
POST http://18.221.172.87/building/
Content-Type: application/json

{
  "b_type_floor": 3,
  "b_age": 15,
  "b_water_coverage": 1,
  "b_ins_sum": 500000,
  "b_prev_claims": 1,
  "b_mortgage": 1
}


### Full property insurance proposals
POST http://18.221.172.87/fullprop/
Content-Type: application/json

{
  "f_type_floor": 3,
  "fb_age": 15,
  "f_water_coverage": 1,
  "fb_ins_sum": 1500000,
  "fb_prev_claims": 1,
  "fc_ins_sum": 1500000,
  "fc_prev_claims": 1,
  "f_mortgage": 1
}


### Health insurance proposals - local
POST http://127.0.0.1:9999/health/
Content-Type: application/json

{
  "Age": "25/01/1974",
  "Gender": "F",
  "own_client": true
}


### Health insurance proposals - Tunbit
POST http://18.221.172.87/health/
Content-Type: application/json

{
  "Age": "19/03/1973",
  "Gender": "M"
}


### Health insurance proposals - VPS
POST http://52.164.216.215/InsuranceService.svc/GetInsuranceCompanies/
Content-Type: application/json

{
  "Age": "19/03/1973",
  "Gender": "M",
  "Operations": true,
  "Transplant": true,
  "Medicine": true
}


### bestcaptchasolver.com API
# Parameters and values:
# access_token=3C30731306914373BED04F4C4FD4F1AA

GET https://bcsapi.xyz/api/user/balance?access_token=3C30731306914373BED04F4C4FD4F1AA
Content-Type: application/json

{
  "status": "success",
  "balance": "9.5632"
}


### Insurance coverage
POST http://127.0.01:9999/coverage/
Content-Type: application/json

{
  "IdNumber": "309020022",
  "IssueDate": "21/01/20",
  "LeftCountryInThreeYears": "1",
  "PassportIssuedInThreeYears": "1"
}


### Insurance coverage - VPS
POST http://18.221.172.87/coverage/
Content-Type: application/json

{
  "IdNumber": "309020022",
  "IssueDate": "21/01/20",
  "LeftCountryInThreeYears": "1",
  "PassportIssuedInThreeYears": "1"
}

###
Angels Original Mix - Betoko
Colours Tim Engelhardt Remix - Darlyn Vlys
Dystopian Original Mix - Henry Saiz
Adria Original Mix - Pisetzky
Interlude Original Mix - Kris Davis
Dancing In The Dark Strano Remix - Matt Dwellers
Minimalody Original Mix - Frezel
Traffic Original Mix - Beatamines, Fabio Montana
Len Original Mix - Nicolas Masseyeff
